import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const query = searchParams.get('q') || '';
    const status = searchParams.get('status') || '';
    const ward = searchParams.get('ward') || '';

    const supabase = await createClient();

    let q = supabase.from('houses').select('*');

    if (query) {
      q = q.or(
        `house_number.ilike.%${query}%,head_of_family.ilike.%${query}%,address.ilike.%${query}%`
      );
    }
    if (status) q = q.eq('status', status);
    if (ward) q = q.eq('ward_id', ward);

    q = q.order('house_number', { ascending: true });

    const { data: houses, error } = await q;
    if (error) throw error;

    // Build a simple HTML-based PDF (browser print-friendly)
    const rows = (houses || [])
      .map(
        (h: any, i: number) => `
      <tr>
        <td>${i + 1}</td>
        <td>${h.house_number}</td>
        <td>${h.head_of_family}</td>
        <td>${h.address}</td>
        <td>${h.contact_number || '-'}</td>
        <td>${h.status}</td>
        <td>${new Date(h.created_at).toLocaleDateString('en-IN')}</td>
      </tr>`
      )
      .join('');

    const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Census Report — Janganana</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Segoe UI', system-ui, sans-serif; padding: 40px; color: #0f172a; }
    .header { text-align: center; margin-bottom: 32px; border-bottom: 3px solid #f97316; padding-bottom: 16px; }
    .header h1 { font-size: 24px; color: #0f172a; margin-bottom: 4px; }
    .header p { font-size: 12px; color: #64748b; }
    .meta { display: flex; justify-content: space-between; margin-bottom: 16px; font-size: 11px; color: #64748b; }
    table { width: 100%; border-collapse: collapse; font-size: 12px; }
    th { background: #0f172a; color: #fff; padding: 8px 10px; text-align: left; font-weight: 600; }
    td { padding: 7px 10px; border-bottom: 1px solid #e2e8f0; }
    tr:nth-child(even) td { background: #f8fafc; }
    .footer { margin-top: 32px; text-align: center; font-size: 10px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 12px; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <div class="header">
    <h1>जनगणना — Census Survey Report</h1>
    <p>Janganana Census Mapping Dashboard</p>
  </div>
  <div class="meta">
    <span>Generated: ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })}</span>
    <span>Total Records: ${(houses || []).length}</span>
  </div>
  <table>
    <thead>
      <tr>
        <th>#</th>
        <th>House No.</th>
        <th>Head of Family</th>
        <th>Address</th>
        <th>Contact</th>
        <th>Status</th>
        <th>Date</th>
      </tr>
    </thead>
    <tbody>
      ${rows || '<tr><td colspan="7" style="text-align:center;padding:20px;color:#94a3b8;">No data found</td></tr>'}
    </tbody>
  </table>
  <div class="footer">
    <p>This report was generated by Janganana Census Dashboard</p>
  </div>
  <script>window.onload = function() { window.print(); }</script>
</body>
</html>`;

    return new NextResponse(html, {
      headers: {
        'Content-Type': 'text/html; charset=utf-8',
      },
    });
  } catch (err: any) {
    return NextResponse.json({ error: err.message || 'PDF export failed' }, { status: 500 });
  }
}
